Repository f-lab-edu/FoodEats, pull requests merged in 2021-08, with the labels that each got.

#29 [#28] User 로직 리팩토링
  src/main/java/com/flab/foodeats/temporary/AppConfig.java
  src/main/java/com/flab/foodeats/temporary/OrderApp.java
  src/main/java/com/flab/foodeats/temporary/discount/DiscountPolicy.java
  src/main/java/com/flab/foodeats/temporary/discount/FixDiscountPolicy.java
  src/main/java/com/flab/foodeats/temporary/discount/RateDiscountPolicy.java
  src/main/java/com/flab/foodeats/temporary/member/Grade.java
  src/main/java/com/flab/foodeats/temporary/member/Member.java
  src/main/java/com/flab/foodeats/temporary/member/MemberRepository.java
  src/main/java/com/flab/foodeats/temporary/member/MemberService.java
  src/main/java/com/flab/foodeats/temporary/member/MemberServiceImpl.java
  src/main/java/com/flab/foodeats/temporary/member/MemoryMemberRepository.java
  src/main/java/com/flab/foodeats/temporary/order/Order.java
  src/main/java/com/flab/foodeats/temporary/order/OrderGrade.java
  src/main/java/com/flab/foodeats/temporary/order/OrderGradeImpl.java
  src/main/java/com/flab/foodeats/temporary/order/OrderRepository.java
  src/main/java/com/flab/foodeats/temporary/order/OrderRepositoryImpl.java
  src/main/java/com/flab/foodeats/temporary/order/OrderService.java
  src/main/java/com/flab/foodeats/temporary/order/OrderServiceImpl.java
  src/main/java/com/flab/foodeats/user/controller/MemberControllerImpl.java
  src/main/java/com/flab/foodeats/user/controller/UserController.java
  src/main/java/com/flab/foodeats/user/controller/UserControllerImpl.java
  src/main/java/com/flab/foodeats/user/controller/advice/ErrorAdvice.java
  src/main/java/com/flab/foodeats/user/filter/FilterAuth.java
  src/main/java/com/flab/foodeats/user/interceptor/AuthInterceptor.java
  src/main/java/com/flab/foodeats/user/interceptor/LoginCheckInterceptor.java
  src/main/java/com/flab/foodeats/user/interceptor/UserLoginAuth.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/Auth.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/AuthErrorCheck.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/AuthPreHandler.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/AuthSessionControl.java
  src/main/java/com/flab/foodeats/user/mapper/MemberMapper.java
  src/main/java/com/flab/foodeats/user/mapper/UserMapper.java
  src/main/java/com/flab/foodeats/user/model/ApiResponse.java
  src/main/java/com/flab/foodeats/user/model/DeleteFormDTO.java
  src/main/java/com/flab/foodeats/user/model/InsertFormDTO.java
  src/main/java/com/flab/foodeats/user/model/LoginFormDTO.java
  src/main/java/com/flab/foodeats/user/model/ResponseResult.java
  src/main/java/com/flab/foodeats/user/model/ResponseStatus.java
  src/main/java/com/flab/foodeats/user/model/UpdateFormDTO.java
  src/main/java/com/flab/foodeats/user/model/code/ErrorUserCode.java
  src/main/java/com/flab/foodeats/user/model/code/StatusUserCode.java
  src/main/java/com/flab/foodeats/user/model/code/SuccessUserCode.java
  src/main/java/com/flab/foodeats/user/service/InsertErrorCheck.java
  src/main/java/com/flab/foodeats/user/service/LoginErrorCheck.java
  src/main/java/com/flab/foodeats/user/service/UserService.java
  src/main/java/com/flab/foodeats/user/service/UserServiceImpl.java
  src/main/java/com/flab/foodeats/user/util/WebConfig.java
Labels: feature, refactor

#36 [#35] Shop(가맹점) 구현
  src/main/java/com/flab/foodeats/global/ApiResponse.java
  src/main/java/com/flab/foodeats/global/StatusCode.java
  src/main/java/com/flab/foodeats/shop/controller/ShopController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/model/ShopDeleteDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopInfoListByIdDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopOpenStatusDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopRegistrationDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopUpdateDTO.java
  src/main/java/com/flab/foodeats/shop/model/code/ErrorShopCode.java
  src/main/java/com/flab/foodeats/shop/model/code/SuccessShopCode.java
  src/main/java/com/flab/foodeats/shop/service/ShopErrorCheck.java
  src/main/java/com/flab/foodeats/shop/service/ShopService.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/user/controller/UserControllerImpl.java
  src/main/java/com/flab/foodeats/user/controller/advice/ErrorAdvice.java
  src/main/java/com/flab/foodeats/user/interceptor/AuthInterceptor.java
  src/main/java/com/flab/foodeats/user/model/code/StatusUserCode.java
  src/main/java/com/flab/foodeats/user/service/UserService.java
  src/main/java/com/flab/foodeats/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#38 [#37] Shop(가맹점) 검색 구현
  src/main/java/com/flab/foodeats/shop/controller/ShopSearchController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopSearchControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopSearchMapper.java
  src/main/java/com/flab/foodeats/shop/service/ShopSearchService.java
  src/main/java/com/flab/foodeats/shop/service/ShopSearchServiceImpl.java
  src/main/resources/mapper/xml/ShopSearchMapper.xml
Labels: feature

#34 [#33] 패스워드 암호화
  build.gradle
  src/main/java/com/flab/foodeats/user/model/InsertFormDTO.java
  src/main/java/com/flab/foodeats/user/model/UpdateFormDTO.java
  src/main/java/com/flab/foodeats/user/service/InsertErrorCheck.java
  src/main/java/com/flab/foodeats/user/service/LoginErrorCheck.java
  src/main/java/com/flab/foodeats/user/service/UserPasswordEncoder.java
  src/main/java/com/flab/foodeats/user/service/UserServiceImpl.java
  src/main/java/com/flab/foodeats/user/util/WebSecurityConfig.java
Labels: feature

#48 [#47] 로그인 코드 스타일 변경
  src/main/java/com/flab/foodeats/user/advice/ErrorAdvice.java
  src/main/java/com/flab/foodeats/user/controller/UserController.java
  src/main/java/com/flab/foodeats/user/controller/UserControllerImpl.java
  src/main/java/com/flab/foodeats/user/interceptor/AuthInterceptor.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/Auth.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/AuthErrorCheck.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/AuthRequired.java
  src/main/java/com/flab/foodeats/user/mapper/UserMapper.java
  src/main/java/com/flab/foodeats/user/service/UserService.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserController.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserControllerImpl.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserService.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserServiceImpl.java
  src/main/resources/mapper/xml/mapper.xml
Labels: style

#39 [#33] 패스워드 암호화 (sha256)
  src/main/java/com/flab/foodeats/user/service/LoginErrorCheck.java
  src/main/java/com/flab/foodeats/user/service/UserInfoEncoder.java
  src/main/java/com/flab/foodeats/user/service/UserPasswordEncoder.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserServiceImpl.java
Labels: feature

#45 [#33] #39 비밀번호 암호화
  src/main/java/com/flab/foodeats/user/service/LoginErrorCheck.java
  src/main/java/com/flab/foodeats/user/service/UserInfoEncoder.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserControllerImpl.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserServiceImpl.java
Labels: refactor

#51 Style/46 shop login add
  src/main/java/com/flab/foodeats/user/advice/ErrorAdvice.java
  src/main/java/com/flab/foodeats/user/model/DeleteFormDTO.java
  src/main/java/com/flab/foodeats/user/model/UpdateFormDTO.java
  src/main/java/com/flab/foodeats/user/util/WebConfig.java
Labels: style

#43 [#42] 가맹점 검색 기능 수정/추가
  src/main/java/com/flab/foodeats/shop/controller/ShopSearchController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopSearchControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopSearchMapper.java
  src/main/java/com/flab/foodeats/shop/search/controller/ShopSearchControllerImpl.java
  src/main/java/com/flab/foodeats/shop/search/controller/advice/ShopSearchErrorAdvice.java
  src/main/java/com/flab/foodeats/shop/search/mapper/ShopSearchMapper.java
  src/main/java/com/flab/foodeats/shop/search/model/SearchShopResultDTO.java
  src/main/java/com/flab/foodeats/shop/search/model/code/SearchErrorCode.java
  src/main/java/com/flab/foodeats/shop/search/service/ShopSearchErrorCheck.java
  src/main/java/com/flab/foodeats/shop/search/service/ShopSearchService.java
  src/main/java/com/flab/foodeats/shop/search/service/ShopSearchServiceImpl.java
  src/main/java/com/flab/foodeats/shop/service/ShopSearchService.java
  src/main/java/com/flab/foodeats/shop/service/ShopSearchServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/xml/ShopSearchMapper.xml
Labels: refactor, feature

#52 [#46] 가맹점 로그인 세션 분리 및 shopId 추가
  src/main/java/com/flab/foodeats/user/filter/FilterAuth.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/Auth.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/ShopAuth.java
  src/main/java/com/flab/foodeats/user/mapper/UserMapper.java
  src/main/java/com/flab/foodeats/user/user/shop/ShopUserController.java
  src/main/java/com/flab/foodeats/user/user/shop/ShopUserControllerImpl.java
  src/main/java/com/flab/foodeats/user/user/shop/ShopUserService.java
  src/main/java/com/flab/foodeats/user/user/shop/ShopUserServiceImpl.java
  src/main/resources/mapper/xml/mapper.xml
Labels: feature

#54 [#52] 피드백 반영 / 가맹점 로그인 코드 수정
  src/main/java/com/flab/foodeats/user/aop/LoginAuth.java
  src/main/java/com/flab/foodeats/user/interceptor/AuthInterceptor.java
  src/main/java/com/flab/foodeats/user/interceptor/auth/AuthSessionControl.java
  src/main/java/com/flab/foodeats/user/user/consumer/ConsumerUserService.java
  src/main/java/com/flab/foodeats/user/user/shop/ShopUserController.java
  src/main/java/com/flab/foodeats/user/user/shop/ShopUserControllerImpl.java
Labels: refactor, style

#55 [#53] 가맹점 필수정보 등록/수정/삭제
  src/main/java/com/flab/foodeats/shop/Interceptor/ShopInterceptor.java
  src/main/java/com/flab/foodeats/shop/controller/ShopController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/model/EssentialShopInfo.java
  src/main/java/com/flab/foodeats/shop/model/ShopDeleteDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopInfoListByIdDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopOpenStatusDTO.java
  src/main/java/com/flab/foodeats/shop/model/ShopRegistrationDTO.java
  src/main/java/com/flab/foodeats/shop/model/code/SuccessShopCode.java
  src/main/java/com/flab/foodeats/shop/service/ShopErrorCheck.java
  src/main/java/com/flab/foodeats/shop/service/ShopService.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/shop/util/ShopWebConfig.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#56 [#53] 가맹점 상태 정보
  src/main/java/com/flab/foodeats/shop/controller/ShopController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/model/StatusShopInfo.java
  src/main/java/com/flab/foodeats/shop/service/ShopService.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#59 [#53] 가맹점 편리 정보
  src/main/java/com/flab/foodeats/shop/controller/ShopController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/model/ConvenientShopInfo.java
  src/main/java/com/flab/foodeats/shop/service/ShopService.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#57 [#49] 가맹점 검색 기능 수정
  src/main/java/com/flab/foodeats/search/controller/ShopSearchControllerImpl.java
  src/main/java/com/flab/foodeats/search/controller/advice/ShopSearchErrorAdvice.java
  src/main/java/com/flab/foodeats/search/interceptor/ShopSearchInterceptor.java
  src/main/java/com/flab/foodeats/search/mapper/ShopSearchMapper.java
  src/main/java/com/flab/foodeats/search/model/SearchShopResultDTO.java
  src/main/java/com/flab/foodeats/search/model/code/SearchErrorCode.java
  src/main/java/com/flab/foodeats/search/service/ShopSearchErrorCheck.java
  src/main/java/com/flab/foodeats/search/service/ShopSearchService.java
  src/main/java/com/flab/foodeats/search/service/ShopSearchServiceImpl.java
  src/main/java/com/flab/foodeats/search/util/ShopSearchWebConfig.java
  src/main/java/com/flab/foodeats/shop/controller/ShopController.java
  src/main/java/com/flab/foodeats/shop/controller/ShopControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/model/ShopDeliveryLocation.java
  src/main/java/com/flab/foodeats/shop/model/ShopDeliveryLocationParam.java
  src/main/java/com/flab/foodeats/shop/search/mapper/ShopSearchMapper.java
  src/main/java/com/flab/foodeats/shop/search/service/ShopSearchService.java
  src/main/java/com/flab/foodeats/shop/search/service/ShopSearchServiceImpl.java
  src/main/java/com/flab/foodeats/shop/service/ShopService.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/user/mapper/UserMapper.java
  src/main/resources/application.yml
  src/main/resources/mapper/xml/ShopSearchMapper.xml
  src/main/resources/mapper/xml/mapper.xml
Labels: feature

#63 [#62] 로그인/ 가맹점 코드 리팩토링
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/model/ConvenientShopInfo.java
  src/main/java/com/flab/foodeats/shop/model/EssentialShopInfo.java
  src/main/java/com/flab/foodeats/shop/model/StatusShopInfo.java
  src/main/java/com/flab/foodeats/shop/model/code/ErrorShopCode.java
  src/main/java/com/flab/foodeats/shop/service/ShopErrorCheck.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/user/mapper/UserMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
  src/main/resources/mapper/xml/mapper.xml
Labels: refactor

#60 [#58] 가맹점 메뉴 등록
  src/main/java/com/flab/foodeats/menu/controller/MenuController.java
  src/main/java/com/flab/foodeats/menu/controller/MenuControllerImpl.java
  src/main/java/com/flab/foodeats/menu/mapper/MenuMapper.java
  src/main/java/com/flab/foodeats/menu/model/MenuEssentialParam.java
  src/main/java/com/flab/foodeats/menu/model/MenuOptionParam.java
  src/main/java/com/flab/foodeats/menu/model/MenuRegisterParam.java
  src/main/java/com/flab/foodeats/menu/model/code/SuccessMenuCode.java
  src/main/java/com/flab/foodeats/menu/service/MenuService.java
  src/main/java/com/flab/foodeats/menu/service/MenuServiceImpl.java
  src/main/resources/mapper/xml/ShopMenuMapper.xml
Labels: feature

#64 [#41] 공휴일/대체 공휴일/ 주말 배달팁 적용
  build.gradle
  src/main/java/com/flab/foodeats/shop/holiday/HolidayCheck.java
  src/main/java/com/flab/foodeats/shop/holiday/WeekendCheck.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
Labels: feature

#67 [#25] 로그인 테스트 코드 수정
  src/test/java/com/flab/foodeats/user/controller/ConsumerUserControllerImplTest.java
  src/test/java/com/flab/foodeats/user/service/ConsumerUserServiceImplTest.java
  src/test/java/com/flab/foodeats/user/service/UserServiceImplTest.java
Labels: bug, refactor

#65 [#61] 가맹점 메뉴 수정 및 삭제
  src/main/java/com/flab/foodeats/menu/controller/MenuController.java
  src/main/java/com/flab/foodeats/menu/controller/MenuControllerImpl.java
  src/main/java/com/flab/foodeats/menu/mapper/MenuMapper.java
  src/main/java/com/flab/foodeats/menu/model/code/SuccessMenuCode.java
  src/main/java/com/flab/foodeats/menu/service/MenuService.java
  src/main/java/com/flab/foodeats/menu/service/MenuServiceImpl.java
  src/main/resources/mapper/xml/ShopMenuMapper.xml
Labels: feature

#66 [#40] 가게 운영 상태 자동 변경
  src/main/java/com/flab/foodeats/shop/autostatus/ShopAutomaticStatus.java
  src/main/java/com/flab/foodeats/shop/controller/ShopControllerImpl.java
  src/main/java/com/flab/foodeats/shop/mapper/ShopMapper.java
  src/main/java/com/flab/foodeats/shop/service/ShopService.java
  src/main/java/com/flab/foodeats/shop/service/ShopServiceImpl.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#71 [#53] 가맹점 필수정보 등록
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/api/shop/dto/RegisterEssentialRequest.java
  src/main/java/com/flab/foodeats/application/shop/RegisterEssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/domain/shop/Essential.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/application.yml
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#72 [#53] 가맹점 필수정보 수정
  src/main/java/com/flab/foodeats/api/shop/RegisterEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/UpdateEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/UpdateEssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#73 [#53] 가맹점 필수정보 삭제
  src/main/java/com/flab/foodeats/api/shop/DeleteEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/RegisterEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/UpdateEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/DeleteEssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#74 [#53] 가맹정 상태정보 등록
  src/main/java/com/flab/foodeats/api/shop/RegisterStatusRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/RegisterStatusTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/domain/shop/Status.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#75 [#53] dto 클래스 통합
  src/main/java/com/flab/foodeats/api/shop/EssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/RegisterEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/StatusRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/EssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/StatusTarget.java
  src/main/java/com/flab/foodeats/application/shop/UpdateEssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
Labels: feature

#76 [#53] 가맹점 상태정보 수정
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#84 [#40] 가맹점 운영 상태 자동변경 / 테스트 코드
  src/test/java/com/flab/foodeats/application/shop/holiday/PublicHolidayTest.java
Labels: test

#83 [#40] 가맹점 운영 상태 자동 변경 사용
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/common/response/ApiResponse.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
  src/test/java/com/flab/foodeats/application/shop/holiday/PublicHolidayTest.java
Labels: feature

#82 [#40] 가맹점 운영 상태 자동 변경
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/autostatus/ShopAutomaticStatus.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/common/response/ApiResponse.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
  src/test/java/com/flab/foodeats/application/shop/holiday/PublicHolidayTest.java
Labels: feature

#87 [#86] shop 가맹점 코드 리팩토링
  src/main/java/com/flab/foodeats/api/shop/ConvenientRequest.java
  src/main/java/com/flab/foodeats/api/shop/StatusRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/ConvenientTarget.java
  src/main/java/com/flab/foodeats/application/shop/EssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/StatusTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/common/response/ErrorUserCode.java
  src/main/java/com/flab/foodeats/domain/shop/Convenient.java
  src/main/java/com/flab/foodeats/domain/shop/Essential.java
  src/main/java/com/flab/foodeats/domain/shop/Status.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: refactor

#88 대체공휴일/공휴일 오류 수정
  src/main/java/com/flab/foodeats/application/shop/holiday/PublicHoliday.java
Labels: fix

#79 [#58] 메뉴 등록 entity, mapper 작성
  src/main/java/com/flab/foodeats/domain/menu/Menu.java
  src/main/java/com/flab/foodeats/domain/menu/MenuOption.java
  src/main/java/com/flab/foodeats/infra/menu/MenuMapper.java
  src/main/java/com/flab/foodeats/infra/menu/MenuOptionMapper.java
  src/main/resources/mapper/xml/MenuMapper.xml
  src/main/resources/mapper/xml/MenuOptionMapper.xml
  src/main/resources/sql/menu.txt
Labels: feature

#80 [#58] 메뉴등록 application단 작성
  src/main/java/com/flab/foodeats/application/menu/EssentialMenuTarget.java
  src/main/java/com/flab/foodeats/application/menu/OptionTarget.java
  src/main/java/com/flab/foodeats/application/menu/adapter/MenuOptionServiceImpl.java
  src/main/java/com/flab/foodeats/application/menu/adapter/MenuServiceImpl.java
  src/main/java/com/flab/foodeats/application/menu/port/MenuOptionService.java
  src/main/java/com/flab/foodeats/application/menu/port/MenuService.java
Labels: feature

#81 [#58] 메뉴 등록 api 작성
  src/main/java/com/flab/foodeats/api/menu/EssentialMenuRequest.java
  src/main/java/com/flab/foodeats/api/menu/OptionRequest.java
  src/main/java/com/flab/foodeats/api/menu/adapter/MenuController.java
  src/main/java/com/flab/foodeats/api/menu/adapter/MenuOptionController.java
Labels: feature
