Repository f-lab-edu/FoodEats, pull requests merged in 2021-09, with the labels that each got.

#96 [#94] Menu 등록 수정 삭제 test 코드 작성
  src/test/java/com/flab/foodeats/application/menu/adapter/MenuServiceImplTest.java
Labels: test

#90 [#40] 가맹점 운영상태 자동변환 테스트 코드
  src/test/java/com/flab/foodeats/application/shop/autostatus/ShopAutomaticStatusTest.java
Labels: test

#89 [#53] Shop 가맹점 테스트 코드
  src/main/java/com/flab/foodeats/domain/shop/Status.java
  src/test/java/com/flab/foodeats/application/shop/adapter/ShopServiceImplTest.java
Labels: test

#97 [#86] Shop 리팩토링 / URL 및 권한 검증
  src/main/java/com/flab/foodeats/api/shop/ConvenientRequest.java
  src/main/java/com/flab/foodeats/api/shop/DeleteEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/EssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/StatusRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/ConvenientTarget.java
  src/main/java/com/flab/foodeats/application/shop/DeleteEssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/EssentialTarget.java
  src/main/java/com/flab/foodeats/application/shop/StatusTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/application/user/LoginUserTarget.java
  src/main/java/com/flab/foodeats/domain/shop/Essential.java
  src/main/java/com/flab/foodeats/domain/user/User.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/java/com/flab/foodeats/infra/user/UserMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
  src/main/resources/mapper/xml/UserMapper.xml
  src/test/java/com/flab/foodeats/application/shop/adapter/ShopServiceImplTest.java
Labels: refactor, feature

#102 [#100] 직접 만든 세션 사용 및 레디스 저장
  src/main/java/com/flab/foodeats/common/util/RedisSessionRepository.java
  src/main/java/com/flab/foodeats/common/util/SessionManager.java
Labels: feature

#91 [#58] 메뉴 기능 추가 및 수정
  src/main/java/com/flab/foodeats/api/menu/EssentialMenuRequest.java
  src/main/java/com/flab/foodeats/api/menu/MenuCode.java
  src/main/java/com/flab/foodeats/api/menu/adapter/MenuController.java
  src/main/java/com/flab/foodeats/application/menu/EssentialMenuTarget.java
  src/main/java/com/flab/foodeats/application/menu/adapter/MenuServiceImpl.java
  src/main/java/com/flab/foodeats/application/menu/port/MenuService.java
  src/main/java/com/flab/foodeats/common/error/exception/UnauthorizedException.java
  src/main/java/com/flab/foodeats/domain/menu/Menu.java
  src/main/resources/application.yml
  src/main/resources/mapper/xml/MenuMapper.xml
  src/main/resources/mapper/xml/ShopMapper.xml
Labels: feature

#92 [#58] 메뉴 옵션 기능 추가 및 수정
  src/main/java/com/flab/foodeats/api/menu/OptionRequest.java
  src/main/java/com/flab/foodeats/api/menu/adapter/MenuOptionController.java
  src/main/java/com/flab/foodeats/application/menu/OptionTarget.java
  src/main/java/com/flab/foodeats/application/menu/adapter/MenuOptionServiceImpl.java
  src/main/java/com/flab/foodeats/application/menu/port/MenuOptionService.java
  src/main/java/com/flab/foodeats/domain/menu/MenuOption.java
  src/main/java/com/flab/foodeats/infra/menu/MenuOptionMapper.java
  src/main/resources/mapper/xml/MenuOptionMapper.xml
Labels: feature

#98 [#86] 가맹점 엔티티 네임 리팩토링
  sql/shop.sql
  src/main/java/com/flab/foodeats/api/shop/BusinessHourRequest.java
  src/main/java/com/flab/foodeats/api/shop/DeleteEssentialRequest.java
  src/main/java/com/flab/foodeats/api/shop/DeleteShopInfoRequest.java
  src/main/java/com/flab/foodeats/api/shop/ShopDeliveryRequest.java
  src/main/java/com/flab/foodeats/api/shop/ShopInfoRequest.java
  src/main/java/com/flab/foodeats/api/shop/adapter/ShopApi.java
  src/main/java/com/flab/foodeats/application/shop/BusinessHourTarget.java
  src/main/java/com/flab/foodeats/application/shop/DeleteShopInfoTarget.java
  src/main/java/com/flab/foodeats/application/shop/ShopDeliveryTarget.java
  src/main/java/com/flab/foodeats/application/shop/ShopInfoTarget.java
  src/main/java/com/flab/foodeats/application/shop/adapter/ShopServiceImpl.java
  src/main/java/com/flab/foodeats/application/shop/autostatus/ShopAutomaticStatus.java
  src/main/java/com/flab/foodeats/application/shop/port/ShopService.java
  src/main/java/com/flab/foodeats/common/response/ErrorUserCode.java
  src/main/java/com/flab/foodeats/domain/shop/BusinessHour.java
  src/main/java/com/flab/foodeats/domain/shop/Shop.java
  src/main/java/com/flab/foodeats/domain/shop/ShopDelivery.java
  src/main/java/com/flab/foodeats/infra/shop/ShopMapper.java
  src/main/resources/mapper/xml/ShopMapper.xml
  src/test/java/com/flab/foodeats/application/shop/autostatus/ShopAutomaticBusinessHourTest.java
Labels: refactor

#101 [#100] Redis 세션 구현
  build.gradle
  src/main/java/com/flab/foodeats/api/user/adapter/ConsumerApi.java
  src/main/java/com/flab/foodeats/api/user/adapter/MerchantApi.java
  src/main/java/com/flab/foodeats/api/user/adapter/RiderApi.java
  src/main/java/com/flab/foodeats/common/auth/AuthInfo.java
  src/main/java/com/flab/foodeats/common/auth/AuthInterceptor.java
  src/main/java/com/flab/foodeats/common/config/RedisSessionConfig.java
  src/main/java/com/flab/foodeats/common/util/RedisSessionRepository.java
  src/main/java/com/flab/foodeats/common/util/SessionManager.java
  src/main/resources/application.yml
Labels: feature
